apiVersion: v2
name: umbrela
description: Helm Umbrella chart
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0

# The appVersion can either match the version of the application being deployed or be different from the Helm chart version. 
# The Helm chart version is defined separately and may not always align with the application version it packages. 
# This separation allows you to track updates to the Helm chart independently from application updates. The appVersion field is optional.
appVersion: "umbrella-1.0.0"

dependencies:
  - name: ms1
    version: "1.3.0"
    repository: https://charts.com/repository/helm_chart_repo/ms1
    condition: ms1.enabled
  - name: ms2
    version: "1.3.0"
    repository: https://charts.com/repository/helm_chart_repo/ms2
    condition: ms2.enabled
  - name: ms3
    version: "1.2.0"
    repository: https://charts.com/repository/helm_chart_repo/ms3
    condition: ms3.enabled
  - name: ms4
    version: "1.3.1"
    repository: https://charts.com/repository/helm_chart_repo/ms4
    condition: ms4.enabled