apiVersion: v2
name: portal
description: An Umbrella Helm chart
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: kubernetes-dashboard
  version: 7.11.1
  repository: https://kubernetes.github.io/dashboard